### ISSUE TITLE
Module vim has wrong sha256sum

### ISSUE THREAD

**Issue by mwgrient** [lunar-linux/moonbase-core#1396]
root@tulp ~ # lunar renew
Starting update of installed modules
The following modules will be updated:
vim
Do you wish to edit the update queue ?  [n] n
Checking dependencies for vim 
Building vim version 8.0
! sha256sum check failed for vim-8.0.tar.bz2
You should remove vim-8.0.tar.bz2 !
vim: Remove "/var/spool/lunar/vim-8.0.tar.bz2" ?  [y] y

Creating /var/log/lunar/compile/vim-8.0.xz 
! Problem detected during PRE_BUILD

cheers, Marco

**Comment by v4hn** [comment]
WTF? I have the old file around.

https://gist.github.com/v4hn/2f2b8804ee05c9b201f756569f452a77

They did a whole new release with all these changes O.o

**Comment by v4hn** [comment]
#1397
