### ISSUE TITLE
tar is only using one core of my processor?

### ISSUE THREAD

**Issue by mwgrient** [lunar-linux/moonbase-core#1415]
Is it correct that tar is using one of my cores (I am talking processor here :-)). And not all of them?
When a package is created after a succesfull build, the process shows in htop 100% in one core. I have 4 cores (Intel(R) Core(TM) i5-3470T CPU @ 2.90GHz).
Regards, Marco.

**Comment by v4hn** [comment]
The time is spent on xz compression and not directly in tar.
For compression of the logs you might be interested in the lunar option `COMPRESS_XZ` in the feature menu of `lunar`.
If you disable it, the logs will be bz2-compressed. This imposes much less computational load, but it also increases the size of your lunar logs.

**Comment by mwgrient** [comment]
Thanks for the info v4hn. pitty lunar-linux is not using pxz for example :-) 
I have learned that this compressor is using all the cores and speed things up, certainly faster for example the kernel and chromium browser. 
But the knowledge is here! Again, thanks.

**Comment by v4hn** [comment]
> Thanks for the info v4hn. pitty lunar-linux is not using pxz for example :-)

Feel free to change this. I would welcome such a request! :-)

**Comment by mwgrient** [comment]
Since version 5.2.0 of XZ, paralel compression is enabled, but not by default. Using it needs de switch --threads / -T . And then you have multi core compression.

Some additional info:
http://www.phoronix.com/scan.php?page=news_item&px=MTg3MDM

I shall try to change it :-)

**Comment by v4hn** [comment]
cool, I didn't know that. Thanks for the info :)

**Comment by mwgrient** [comment]
Hopefully, end this month I can buy a secondhand laptop to work with Lunar Linux again. Maybe I can help with this feature!

**Comment by v4hn** [comment]
On Thu, May 11, 2017 at 09:40:00AM -0700, mwgrient wrote:
> Hopefully, end this month I can buy a secondhand laptop to work with Lunar Linux again. Maybe I can help with this feature!

Sorry for the timeout. Yes, it would be nice to have this as an option in the lunar module.
Feel free to create a pull-request if you manage to patch it into the tool :)

**Comment by mwgrient** [comment]
I have a laptop now. As soon as I can install Lunar Linux (LL), I will have a look at the options I have. Thanks for the invitation :-)
