### ISSUE TITLE
 kbd- outdated and not found

### ISSUE THREAD

**Issue by mwgrient** [lunar-linux/moonbase-core#1454]
kbd (in moonbase core/utils) looks outdated and can not be found, moonbase offers 2.0.3, but:

This is the latest: 08-Jan-2017 18:46 - source, http://kbd-project.org/

> http://kbd-project.org/download/kbd-2.0.4.tar.xz  
> sha1 - 5fd90af6beb225a9bb9b9fb414c090fba53c9a55793e172f508cd43652e59a88

regards.

**Comment by v4hn** [comment]
fixed in 1e6d47ca84a9bdf8c5738706069b6ec8891b797f
