### ISSUE TITLE
ntfsprogs and ntfs-3g

### ISSUE THREAD

**Issue by stumbles** [lunar-linux/moonbase-core#1705]
I think one of these should be removed. ntfs-3g(in other) is the merging of ntsfprogs(core) and the later so ntfsprogs is my vote to go. The merging was done, if the wiki is accurate https://en.wikipedia.org/wiki/NTFS-3G around April 2011.

**Comment by v4hn** [comment]
Well, Tuxera even *calls* their released software [`ntfs-3g_ntfsprogs-2017.3.23`](https://www.tuxera.com/community/open-source-ntfs-3g/).
In my opinion we should just remove `ntfsprogs` and move `ntfs-3g` to core as we discussed on IRC earlier.

**Comment by Florin65** [comment]
The problem was solved now.

**Comment by v4hn** [comment]
right, closing.
