### ISSUE TITLE
vim:build errors

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-core#1885]
> /usr/bin/ld: not found -lieee
collect2: error: ld returned 1 exit status
link.sh: Linking failed
make: *** [Makefile:1950：vim] error 1
Creating /var/log/lunar/compile/vim-8.1.xz 
! Problem detected during BUILD

[vim-8.zip](https://github.com/lunar-linux/moonbase-core/files/2045751/vim-8.zip)

**Comment by Florin65** [comment]
Can't replicate this.
