### ISSUE TITLE
kdoctools:libreadline.so.6

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-core#2232]
[ 36%] Building CXX object src/CMakeFiles/meinproc5.dir/loggingcategory.cpp.o
[ 38%] Linking CXX executable ../bin/meinproc5
[ 38%] Built target KF5DocTools
[ 38%] Built target meinproc5
Scanning dependencies of target po-uk-docs-kf5options-kf5options-7
Scanning dependencies of target po-uk-docs-meinproc5-meinproc5-1
Scanning dependencies of target po-sv-docs-meinproc5-meinproc5-1
Scanning dependencies of target po-sv-docs-kf5options-kf5options-7
Scanning dependencies of target po-uk-docs-qt5options-qt5options-7
[ 39%] Generating po/uk/docs/kf5options/kf5options.7
[ 41%] Generating po/sv/docs/meinproc5/meinproc5.1
[ 42%] Generating po/uk/docs/meinproc5/meinproc5.1
[ 44%] Generating po/sv/docs/kf5options/kf5options.7
[ 45%] Generating po/uk/docs/qt5options/qt5options.7
/usr/bin/xmllint: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
/usr/bin/xmllint: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
/usr/bin/xmllint: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
/usr/bin/xmllint: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
/usr/bin/xmllint: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
kf5.kdoctools: Error: `xmllint --noout` outputted text
kf5.kdoctools: Error: `xmllint --noout` outputted text
kf5.kdoctools: Error: `xmllint --noout` outputted text
kf5.kdoctools: Error: `xmllint --noout` outputted text
make[2]: *** [CMakeFiles/po-sv-docs-meinproc5-meinproc5-1.dir/build.make:63: po/sv/docs/meinproc5/meinproc5.1] Error 1
make[2]: *** [CMakeFiles/po-uk-docs-qt5options-qt5options-7.dir/build.make:63: po/uk/docs/qt5options/qt5options.7] Error 1
make[2]: *** [CMakeFiles/po-uk-docs-meinproc5-meinproc5-1.dir/build.make:63: po/uk/docs/meinproc5/meinproc5.1] Error 1
make[1]: *** [CMakeFiles/Makefile2:226: CMakeFiles/po-uk-docs-qt5options-qt5options-7.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/po-uk-docs-kf5options-kf5options-7.dir/build.make:63: po/uk/docs/kf5options/kf5options.7] Error 1
kf5.kdoctools: Error: `xmllint --noout` outputted text
make[1]: *** [CMakeFiles/Makefile2:112: CMakeFiles/po-uk-docs-kf5options-kf5options-7.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:74: CMakeFiles/po-uk-docs-meinproc5-meinproc5-1.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:150: CMakeFiles/po-sv-docs-meinproc5-meinproc5-1.dir/all] Error 2
make[2]: *** [CMakeFiles/po-sv-docs-kf5options-kf5options-7.dir/build.make:63: po/sv/docs/kf5options/kf5options.7] Error 1
make[1]: *** [CMakeFiles/Makefile2:188: CMakeFiles/po-sv-docs-kf5options-kf5options-7.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

I've actually reinstalled the latest version of readline.

**Comment by dagbrown** [comment]
You have, but everything which depends on readline is supposed to be rebuilt.

libxml2 has a stealth dependency on readline, but I've just submitted a [PR](https://github.com/lunar-linux/moonbase-other/pull/1353) to make it explicit.  In the meantime, you should re-lin libxml2.

**Comment by lhw828** [comment]
Well, wait for PR to merge.

**Comment by florin65** [comment]
Why is this issue added here?
kdoctool is on the kde/frameworks repository.

**Comment by stumbles** [comment]
Dunno why its here. 

The answer is; he needs to do a lunar fix.
