### ISSUE TITLE
upower.service invalid namespace

### ISSUE THREAD

**Issue by stumbles** [lunar-linux/moonbase-core#2349]
Was having an issue with after logging into kde via sddm. Login works but there would be a lengthy pause before the task bar would show up. Also noticed after login and say, launching dolphin it would take 30 seconds or more to show up.

Looking through systemctl status of things, saw upower erroring out on invalid namespace and trying to restart to fast. Some duck-duck-going came across this; https://bbs.archlinux.org/viewtopic.php?id=249932 which leads to this; https://github.com/systemd/systemd/blob/v243/README#L77

So it seems I am considered a private user.

Recompiled the kernel with CONFIG_USER_NS=y and now everything works fine. So might I suggest the dailies iso be altered to have this enabled by default?

**Comment by dagbrown** [comment]
Check out https://github.com/lunar-linux/lunar-iso/pull/64/

I think that might have what you're looking for, along with a ton of other updates.

**Comment by stumbles** [comment]
Thanks. I'm closing this.
