### ISSUE TITLE
some errors about remove module when update

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-core#2437]
Preparing to install moonbase.tar.bz2 ...
Removed module: moonbase
Extracting moonbase.tar.bz2 ...
Created /var/log/lunar/install/moonbase-20200305.03 
Creating /var/log/lunar/md5sum/moonbase-20200305.03
Removed modules:
  ilmbase

Starting update of installed modules
ilmbase was removed from /var/lib/lunar/moonbase
ilmbase: Do you want to remove ilmbase ? [y] 
Removed module: ilmbase
/var/lib/lunar/functions/modules.lunar: line 690: continue: only meaningful in a `for', `while', or `until' loop

**Comment by Ratler** [comment]
This bug should have been fixed. Closing.
