### ISSUE TITLE
linux-firmware:CONFIG_FW_LOADER_COMPRESS is not enabled.

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-core#3112]
Building linux-firmware version 20220809
The kernel option CONFIG_FW_LOADER_COMPRESS is not enabled.
Please reconfigure and rebuild your kernel. Then try installing linux-firmware again.

**Comment by Ratler** [comment]
You just need to recompile your kernel and enable that option, this is not a bug. Just a kernel config change :)
