### ISSUE TITLE
nano:some nano errors

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-core#3204]
Do you wish to edit the update queue ?  [n] y
/var/lib/lunar/functions/edit.lunar: line 86: /bin/nano: No such file or directory

#:whereis nano
#:nano: /usr/bin/nano /usr/share/nano /usr/share/man/man1/nano.1.gz /usr/share/info/nano.info

**Comment by esselfe** [comment]
Can't reproduce, try 'hash -r' or 'ln -sv ../usr/bin/nano /bin/nano'
