### ISSUE TITLE
irssi:It seems that there is some abnormality in the dependency on glib-2

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-core#3313]
It seems that there is some abnormality in the dependency on glib-2

checking for GLIB - version >= 2.32.0... 
*** 'pkg-config --modversion glib-2.0' returned 2.76.0, but GLIB (2.77.0)
*** was found! If pkg-config was correct, then it is best
*** to remove the old version of GLib. You may also be able to fix the error
*** by modifying your LD_LIBRARY_PATH enviroment variable, or by editing
*** /etc/ld.so.conf. Make sure you have run ldconfig if that is
*** required on your system.
*** If pkg-config was wrong, set the environment variable PKG_CONFIG_PATH
*** to point to the correct configuration files
no
*** trying without -lgmodule
checking for pkg-config... (cached) /usr/bin/pkg-config
checking pkg-config is at least version 0.7... yes
checking for GLIB - version >= 2.32.0... 
*** 'pkg-config --modversion glib-2.0' returned 2.76.0, but GLIB (2.77.0)
*** was found! If pkg-config was correct, then it is best
*** to remove the old version of GLib. You may also be able to fix the error
*** by modifying your LD_LIBRARY_PATH enviroment variable, or by editing
*** /etc/ld.so.conf. Make sure you have run ldconfig if that is
*** required on your system.
*** If pkg-config was wrong, set the environment variable PKG_CONFIG_PATH
*** to point to the correct configuration files
no

*** If you don't have GLIB, you can get it from ftp://ftp.gtk.org/pub/glib/
*** We recommend you get the latest stable GLIB 2 version.
*** Compile and install it, and make sure pkg-config finds it,
*** by adding the path where the .pc file is located to PKG_CONFIG_PATH
*** Or alternatively install your distribution's package.

configure: error: GLIB is required to build irssi.

**Comment by stumbles** [comment]
irssi compiles fine here with glib-2-2.76.0.

Suggest recompile glib-2 or lunar fix.
