### ISSUE TITLE
Kmod SOURCE_URL hardcoded

### ISSUE THREAD

**Issue by prototux** [lunar-linux/moonbase-core#810]
In https://github.com/lunar-linux/moonbase-core/blob/master/kernel/kmod/DETAILS , the SOURCE_URL is hardcoded to ftp://ftp.kernel.org, which fail here, it probably should be $KERNEL_URL/pub/linux/utils/kernel/$MODULE.

**Comment by v4hn** [comment]
Fixed by 7268d47787736ab581b1a17395209624a8bb3e82
